name: Build PyTorch-SM3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
    - name: Build with setuptools
      run: python setup.py sdist bdist_wheel
    - name: Upload artifacts (tarball and wheel)
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ./dist/

  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        pytorch-version: [1.4.0, 1.5.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --find-links=https://download.pytorch.org/whl/torch_stable.html torch==${{ matrix.pytorch-version }}+cpu
        pip install -r requirements.txt
    - name: Retrieve artifact
      uses: actions/download-artifacts@v2
      with:
        name: binaries
        path: ./local
    - name: Install new SM3 binary
      run: pip install ./local/torch_SM3-*-py3-none-any.whl
    - name: Test with pytest
      run: |
        pip install pytest==5.4.3
        pytest
