name: Test PyTorch-SM3

on: 
  push:
    branches:
      - simple_CI
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Only want cpu version, so install directly.
        pip install --find-links=https://download.pytorch.org/whl/torch_stable.html torch==1.4.0+cpu
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
